# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    filters:
      # ignore all tags
      tags:
        ignore: /.*/

    docker:
      # specify the version you desire here
      - image: circleci/node:7
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Version patch and tag
          command: | 
            git config user.email "aj.rabe@gmail.com"
            git config user.name "circleci"
            npm version patch
            git push --set-upstream origin ${CIRCLE_BRANCH}

      - run: npm run build

      - store_artifacts:
          path: ~/repo/dist


